#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v21
# autospec commit: e822d6e48dc0
#
Name     : xfsdump
Version  : 3.2.0
Release  : 2
URL      : https://git.kernel.org/pub/scm/fs/xfs/xfsdump-dev.git/snapshot/xfsdump-dev-3.2.0.tar.gz
Source0  : https://git.kernel.org/pub/scm/fs/xfs/xfsdump-dev.git/snapshot/xfsdump-dev-3.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfsdump-bin = %{version}-%{release}
Requires: xfsdump-license = %{version}-%{release}
Requires: xfsdump-locales = %{version}-%{release}
Requires: xfsdump-man = %{version}-%{release}
BuildRequires : attr-dev
BuildRequires : pkgconfig(ncursesw)
BuildRequires : util-linux-dev
BuildRequires : xfsprogs-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
_____________________
See the file doc/INSTALL for build, installation and post-
install configuration steps.

%package bin
Summary: bin components for the xfsdump package.
Group: Binaries
Requires: xfsdump-license = %{version}-%{release}

%description bin
bin components for the xfsdump package.


%package doc
Summary: doc components for the xfsdump package.
Group: Documentation
Requires: xfsdump-man = %{version}-%{release}

%description doc
doc components for the xfsdump package.


%package license
Summary: license components for the xfsdump package.
Group: Default

%description license
license components for the xfsdump package.


%package locales
Summary: locales components for the xfsdump package.
Group: Default

%description locales
locales components for the xfsdump package.


%package man
Summary: man components for the xfsdump package.
Group: Default

%description man
man components for the xfsdump package.


%prep
%setup -q -n xfsdump-dev-3.2.0
cd %{_builddir}/xfsdump-dev-3.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1731616494
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1731616494
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xfsdump
cp %{_builddir}/xfsdump-dev-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/xfsdump/901f4cc558fe3ee50112cdf50c90a17b284c58ce || :
cp %{_builddir}/xfsdump-dev-%{version}/doc/COPYING %{buildroot}/usr/share/package-licenses/xfsdump/f38aac1e64e9f8fdd9037bea6259a999376dd9ad || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang xfsdump

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfsdump
/usr/bin/xfsinvutil
/usr/bin/xfsrestore

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/xfsdump/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xfsdump/901f4cc558fe3ee50112cdf50c90a17b284c58ce
/usr/share/package-licenses/xfsdump/f38aac1e64e9f8fdd9037bea6259a999376dd9ad

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/xfsdump.8
/usr/share/man/man8/xfsinvutil.8
/usr/share/man/man8/xfsrestore.8

%files locales -f xfsdump.lang
%defattr(-,root,root,-)

